In [18]:
import spacy
from sklearn.metrics.pairwise import cosine_similarity


In [3]:
nlp=spacy.load("en_core_web_lg")

In [8]:
doc=nlp("cat dog bread lion prashant table")
for token in doc:
    print(token.text,'vector:',token.has_vector,'oov:',token.is_oov)


cat vector: True oov: False
dog vector: True oov: False
bread vector: True oov: False
lion vector: True oov: False
prashant vector: False oov: True
table vector: True oov: False


In [9]:
doc[1].vector.shape

(300,)

In [10]:
base_token=nlp('bread')

In [13]:
doc1=nlp('sandwich burger car cat tiger wheat bread')
for token in doc1:
    print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

sandwich <-> bread: 0.6341067010130894
burger <-> bread: 0.47520687769584247
car <-> bread: 0.06451532596945217
cat <-> bread: 0.1255933851043781
tiger <-> bread: 0.04764611272488976
wheat <-> bread: 0.615036141030184
bread <-> bread: 0.9999999744752309


In [14]:
def print_similarity(base_word, words_to_compare):
    base_token = nlp(base_word)
    doc = nlp(words_to_compare)
    for token in doc:
        print(f"{token.text} <-> {base_token.text}: ", token.similarity(base_token))

In [15]:
print_similarity("iphone", "apple samsung iphone dog kitten")

apple <-> iphone:  0.4387907748060368
samsung <-> iphone:  0.6708590303423401
iphone <-> iphone:  0.9999999983096304
dog <-> iphone:  0.08211864228011527
kitten <-> iphone:  0.10222317834969896


In [28]:
king = nlp.vocab["king"].vector
man = nlp.vocab["man"].vector
woman = nlp.vocab["woman"].vector
queen = nlp.vocab["queen"].vector

result = king - man + woman

In [29]:
cosine_similarity([result], [queen])

array([[0.06814879]], dtype=float32)

In [23]:
most_similar_word = nlp.vocab.vectors.most_similar(result.reshape(1, -1), n=1)[0][0]

In [24]:
most_similar_word

array([7464393751932445219], dtype=uint64)

In [25]:
most_similar_word_text = nlp.vocab.strings[most_similar_word]

In [26]:
print(most_similar_word_text)

king


In [35]:
cat = nlp.vocab['cat'].vector
baby = nlp.vocab["baby"].vector
kitten=nlp.vocab['kitten'].vector
result1 = cat+baby

In [38]:
cosine_similarity([result1], [kitten])

array([[0.77655965]], dtype=float32)

In [41]:
dog = nlp.vocab['dog'].vector
baby = nlp.vocab["baby"].vector
puppy=nlp.vocab['puppy'].vector
result1 = dog + baby

In [44]:
cosine_similarity([result1], [puppy])

array([[0.91349435]], dtype=float32)

In [43]:
most_similar_word = nlp.vocab.vectors.most_similar(result1.reshape(1, -1), n=1)[0][0]
most_similar_word_text = nlp.vocab.strings[most_similar_word]
print(most_similar_word_text)

dog
